name: Run packer build on a template file

on:
  push:
    branches:
      - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: RichTeaMan/packer-build-action@v1.2
        with:
          templateFile: 'packer-template.pkr.hcl'
          varFile: 'variables.pkr.hcl'
          workingDir: '.'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2

